-- ============================================================
-- V33__fix_half_day_leave_total_days.sql
--
-- Tujuan:
--   Memperbaiki data historis leave_requests untuk jenis cuti
--   "Cuti setengah hari" yang total_days-nya masih tersimpan 1
--   (hari penuh), bukan 0.5 seperti seharusnya.
--
-- Akar masalah (SUDAH DIPERBAIKI di kode -- lihat LeaveService.java
-- createCuti() & createUrgentCuti()):
--   Body request dari frontend cuma mengirim leaveType sebagai
--   { leaveTypeId } saja (tanpa name). Sebelum diperbaiki,
--   cuti.getLeaveType() di titik calculateLeaveDays() dipanggil
--   masih berupa objek mentah hasil deserialize JSON itu -- field
--   "name"-nya NULL karena memang tidak dikirim frontend, BUKAN
--   diambil dari database. Akibatnya pengecekan nama jenis cuti
--   ("cuti setengah hari") tidak pernah cocok, dan durasinya
--   dihitung sebagai hari kerja biasa (1 hari), bukan 0,5.
--
--   Untuk pengajuan MANDIRI karyawan (createCuti/ApplyCuti), nilai
--   yang salah ini sempat "ke-fix" ulang otomatis saat approval
--   3 tingkat (Leader->SPV->Manager) selesai, karena
--   processApprovalAction() menghitung ulang totalDays memakai
--   entity yang sudah benar-benar diambil dari database (bukan
--   objek mentah JSON) -- makanya Sisa Cuti di ApplyCuti sudah
--   BENAR (0,5) untuk kasus ini.
--
--   Untuk Cuti Susulan/Darurat (createUrgentCuti, auto-ACC oleh
--   HR/Super Admin), TIDAK ADA proses approval bertingkat yang
--   memicu perhitungan ulang tersebut -- status langsung APPROVED
--   di method yang sama, jadi nilai total_days = 1 yang salah itu
--   tersimpan PERMANEN ke database. Inilah sebabnya Dashboard,
--   Direktori Karyawan, dan tab Cuti Karyawan (yang semuanya
--   membaca total_days apa adanya dari database, tanpa proses
--   approval ulang) menampilkan Sisa Cuti yang salah (terpotong
--   1 hari penuh, bukan 0,5) untuk cuti setengah hari yang
--   diinput lewat Cuti Susulan.
--
--   Kode sudah diperbaiki (fetch ulang LeaveType dari
--   leaveTypeRepository sebelum calculateLeaveDays() dipanggil,
--   di createCuti() MAUPUN createUrgentCuti()), sehingga
--   pengajuan BARU setelah migrasi ini akan langsung tersimpan
--   benar (0.5). Migrasi ini HANYA membereskan baris yang
--   terlanjur salah tersimpan SEBELUM perbaikan kode berlaku.
--
-- Catatan:
--   - Idempoten: WHERE total_days <> 0.5 membuat migrasi ini
--     aman dijalankan ulang tanpa efek samping kalau datanya
--     sudah benar.
--   - Tidak menyentuh leave_requests.manual_leave_days atau
--     employees.manual_leave_balance -- pada kasus yang ditemukan,
--     saldo Sisa Cuti (lama/manual) karyawan terkait masih 0
--     sehingga porsi manual yang terlanjur dipotong juga 0
--     (lihat LeaveService.allocateManualLeaveOnApproval).
-- ============================================================
UPDATE leave_requests lr
SET total_days = 0.5
FROM leave_types lt
WHERE lr.leave_type_id = lt.leave_type_id
  AND LOWER(lt.name) = LOWER('Cuti setengah hari')
  AND lr.total_days <> 0.5;
